- name: Remove Files from Old Partitions
  block:
    - name:

- name: Remove Installed Packages
  ansible.builtin.package:
    name: "{{ missing_packages }}"
    state: absent
  when: missing_packages | length > 0
